### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by wasgood566** [GitPro10/probot-credit-collector#1]
Can you make a video on youtube and send the link? Explain how it works.

**Comment by GitPro10** [comment]
> Can you make a video on youtube and send the link? Explain how it works.

this is a " secret " project kinda illegal I can't show it in public
Inbox me on Facebook
https://facebook.com/ahmed.jubayer.69

**Comment by wasgood566** [comment]
> > Can you make a video on youtube and send the link? Explain how it works.
> 
> this is a " secret " project kinda illegal I can't show it in public Inbox me on Facebook https://facebook.com/ahmed.jubayer.69

Done, I pmed you.

**Comment by GitPro10** [comment]
Question Answered
